#!/usr/bin/perl

#----------------------------------------------------------------------------------
# Project Name      - PerlProjects/clean-locales
# Started On        - Thu  9 May 21:32:57 BST 2019
# Last Change       - Thu  9 May 22:23:57 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

use strict;
use warnings;
use autodie;
use File::Basename 'basename';
use File::Path 'remove_tree';
use TFL; # <-- libtfl-perl

my $_VERSION_ = "2019-05-09";
my $_PROJECT_ = @{[basename($0)]};

my $DIR = '/usr/share/locale';

sub USAGE{
	my $INFO = qq{            @{[uc($_PROJECT_)]} ($_VERSION_)
		            Written by terminalforlife (terminalforlife\@yahoo.com)

		            Remove some unnecessary non-English localizations.

		SYNTAX:     $_PROJECT_ [OPTS]

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --quiet|-q              - Runs in quiet mode. Errors still output.

		FILES:      Files in '$DIR' will be deleted, except:

		            en_GB
		            en_US
		            locale.alias
	};

	print($INFO =~ tr/\t//dr)
}

my $ROOT = 0;
$ROOT = 1 if $> == 0;
my $QUIET = 0;

while(defined($ARGV[0])){
	if($ARGV[0] =~ /^(--help|-h|-\?)$/){
		USAGE(1); exit 0
	}elsif($ARGV[0] =~ /^(--version|-v)$/){
		print("$_VERSION_\n"); exit 0
	}elsif($ARGV[0] =~ /^(--quiet|-q)$/){
		$QUIET = 1
	}else{
		TFL::FAIL(1, __LINE__, "Incorrect argument(s) specified")
	}

	shift(@ARGV)
}

TFL::FAIL(1, __LINE__, "Root access is required") unless $> == 0;
TFL::FAIL(1, __LINE__, "Directory '$DIR' doesn't exist.") if not -d $DIR;

# $_[0] = The directory or file to process.
# $_[1] = The error string appended to the line.
sub DelIt{
	remove_tree($_[0], {safe => 1}) if -d $_[0];
	unlink($_[0]) if -f $_[0];
	print("$_[1]") if (not $QUIET and -e $_[0])
}

#TODO - Why did this just wipe everything from the directory!?

my @TARGETS = glob($DIR . '/*');
foreach(@TARGETS){
	print("$_  ") if not $QUIET;
	DelIt($_, '[!]') if $_ !~ /^(en_GB|en_US|locale\.alias)$/;
	print("\n") if not $QUIET
}
