#!/usr/bin/env perl
#cito M:755 O:0 G:0 T:/usr/bin/fix-ff-gtk
#----------------------------------------------------------------------------------
# Project Name      - PerlProjects/fix-ff-gtk (Fix Firefox GTK)
# Started On        - Fri 10 Jan 19:32:40 GMT 2020
# Last Change       - Fri 10 Jan 23:51:52 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# A Perl rewrite of the old shell version.
#----------------------------------------------------------------------------------

use strict;
use warnings;
use autodie;
use TFL 'Err', 'YNInput'; # <-- libtfl-perl (>= 2020-01-10)

my $CurVer = "2020-01-10";

my $File = '/usr/bin/firefox';
my $Theme = 'Adwaita';

sub Usage{
	print(qq{            @{[uc($TFL::PROGNAME)]} ($CurVer)
		            $TFL::AUTHOR

		            Psuedo-Fix colors used in Firefox when using a dark GTK theme.

		SYNTAX:     $TFL::PROGNAME [OPTS]

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --theme|-t NAME         - Where NAME is the chosen GTK theme.
		            --non-interactive|-N    - Execute non-interactively.

		NOTE:       The GTK theme Adwaita, which is often available by default, is
		            needed, unless another is specified.

		            This script will work globally, meaning ALL users, regardless
		            of their chosen theme, will use the Adwaita GTK theme for their
		            use of Firefox.

		CAUTION:    It's possible that changes to the below file would not be
		            desired, in which case it would have to be restored from a
		            backup, or Firefox would need to be reinstalled.

		            Using the non-interactive feature assumes yes.

		FILE:       $File
	} =~ tr/\t//dr);
}

my $NonInt = 'false';

while (defined($ARGV[0])){
	if ($ARGV[0] =~ '^(--help|-h|-\?)$'){
		Usage(1); exit(0)
	}elsif ($ARGV[0] =~ '^(--version|-v)$'){
		print("$CurVer\n"); exit(0)
	}elsif ($ARGV[0] =~ '^(--non-interactive|-N)$'){
		$NonInt = 'true'
	}else{
		Err(1, "Incorrect option(s) specified.")
	}

	shift(@ARGV)
}

exit(1) unless YNInput("Make permanent changes to '$File'?") == 0;

Err(1, 'Root access is required.') unless $< == 0;
Err(1, "File '$File' not found.") unless -f $File;

open(my $FH, '+<', $File);

my @Data = <$FH>;

truncate($FH, 0);
seek($FH, 0, 0);

foreach (@Data){
	if (/^[[:space:]]+exec \$MOZ_LIBDIR\/\$MOZ_APP_NAME "\$@"$/){
		print($FH $_ =~ s/^([[:space:]]+)(.*)$/$1 GTK_Theme='Adwaita' $2/r)
	}else{
		print($FH $_)
	}
}

close($FH);
