#!/usr/bin/perl

#----------------------------------------------------------------------------------
# Project Name      - getip/getip.pl
# Started On        - Wed  8 May 14:35:49 BST 2019
# Last Change       - Wed  8 May 22:43:31 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

use strict;
use warnings;
use autodie;
use File::Basename 'basename';
use TFL; # <-- libtfl-perl (>= 2019-05-07)

my $_VERSION_ = "2019-05-08";
my $_PROJECT_ = @{[basename($0)]};

my $DOM = "https://whatismyipaddress.com";

sub USAGE{
	my $INFO = qq{            @{[uc($_PROJECT_)]} ($_VERSION_)
		            Written by terminalforlife (terminalforlife\@yahoo.com)

		            View your internal and/or external IP address.

		SYNTAX:     $_PROJECT_ [OPTS]

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --update|-U             - Check for updates to $_PROJECT_.
		            --internal|-i           - Show only the internal IP address.
		            --external|-e           - Show only the external IP address.
		            --ip-only|-I            - Show only the IP address.

		SITE:       $DOM
	};

	print($INFO =~ tr/\t//dr)
}

my $UPDATE = 0;
my $INTERNAL = 1;
my $EXTERNAL = 1;
my $INTEXT_DETECTED = 0;
my $INTSTR = 'Internal IP: ';
my $EXTSTR = 'External IP: ';

while(defined($ARGV[0])){
	if($ARGV[0] =~ /^(--help|-h|-\?)$/){
		USAGE(); exit 0
	}elsif($ARGV[0] =~ /^(--version|-v)$/){
		print("$_VERSION_\n"); exit 0
	}elsif($ARGV[0] =~ /^(--update|-U)$/){
		$UPDATE = 1
	}elsif($ARGV[0] =~ /^(--internal|-i)$/){
		$INTEXT_DETECTED++;
		$INTERNAL = 1; $EXTERNAL = 0
	}elsif($ARGV[0] =~ /^(--external|-e)$/){
		$INTEXT_DETECTED++;
		$INTERNAL = 0; $EXTERNAL = 1
	}elsif($ARGV[0] =~ /^(--ip-only|-I)$/){
		$INTSTR = ''; $EXTSTR = '';
	}else{
		TFL::FAIL(1, __LINE__, "Incorrect argument(s) specified")
	}

	shift(@ARGV)
}

TFL::FAIL(1, __LINE__, "Either '--internal|-i' or '--external|-e'.")
	if $INTEXT_DETECTED == 2;

my $GH_URL = "https://github.com/terminalforlife/getip/raw/master/version";
TFL::UpdChk($UPDATE, $GH_URL, $_VERSION_);

if($INTERNAL){
	use Net::Address::IP::Local; # <-- libnet-address-ip-local-perl

	print($INTSTR . Net::Address::IP::Local->public() . "\n")
}

if($EXTERNAL){
	use LWP::UserAgent;

	my $UA = LWP::UserAgent->new();
	$UA->max_redirect(1);
	$UA->protocols_allowed(['http', 'https']);
	$UA->agent('Mozilla/5.0');

	my @DATA = split("\n", $UA->get($DOM)->decoded_content());

	foreach(@DATA){
		foreach(@{[split(' ', $_)]}){
			if($_ =~ /[0-9]+\.[0-9]+\.[0-9]+\.[0-9]/){
				print($_ =~ s/(.*)<\/span>$/$EXTSTR$1/r . "\n");
				last
			}
		}
	}
}
