#!/usr/bin/perl

#----------------------------------------------------------------------------------
# Project Name      - perlmisc/lsbins
# Started On        - Thu 25 Apr 14:17:05 BST 2019
# Last Change       - Thu 25 Apr 19:39:37 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

use strict;
use warnings;
use autodie;
use File::Basename 'basename';
use List::MoreUtils 'uniq';

my $_VERSION_ = '2019-04-25';

sub FAIL{
	printf("[L%0.4d] ERROR: %s\n", $_[1], $_[2]);
	if($_[0] == 1){exit 1}
}

sub USAGE{
	my $INFO = qq{            LSBINS ($_VERSION_)
		            Written by terminalforlife (terminalforlife\@yahoo.com)

		            Perl rewrite of shell program 'lsbins'.

		SYNTAX:     lsbins [OPTS]

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
	};

	print(split("\t", $INFO))
}

while($ARGV[0]){
	if($ARGV[0] =~ /^(--help|-h|-\?)$/){
		USAGE;
		exit 0
	}elsif($ARGV[0] =~ /^(--version|-v)$/){
		print("$_VERSION_\n");
		exit 0
	}else{
		FAIL(1, __LINE__, "Incorrect argument(s) specified")
	}

	shift(@ARGV)
}

my @EXECS;
foreach(split(':', $ENV{PATH})){
	foreach(glob("$_/*")){
		if(-f $_ and -x $_ and -r $_){
			push(@EXECS, basename($_, '/'))
		}
	}
}

@EXECS = uniq(sort({lc($a) cmp lc($b)} @EXECS));

my @MANS;
if(-d '/usr/share/man'){
	@MANS = glob('/usr/share/man/man[1-8]/*.[1-8].gz')
}else{
	FAIL(1, __LINE__, "Unable to find the man pages.")
}

my $BUFFER = readpipe("/usr/bin/man -f @EXECS 2> /dev/null");
undef @EXECS;

print($BUFFER =~ s/\([0-8]\)\s+//gr)
