#!/usr/bin/perl

#----------------------------------------------------------------------------------
# Project Name      - PerlProjects/lsbins
# Started On        - Thu 25 Apr 14:17:05 BST 2019
# Last Change       - Sun  1 Dec 21:25:42 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

use strict;
use warnings;
use autodie;
use File::Basename 'basename';
use List::MoreUtils 'uniq';
use TFL; # <-- libtfl-perl (>= 2019-05-16)

my $CurVer = "2019-12-01";
my $Progrm = basename($0);

while($ARGV[0]){
	if($ARGV[0] =~ /^(--help|-h|-\?)$/){
		print("Usage: lsbins [--help|-h|-? | --version|-v]\n");
		exit(0)
	}elsif($ARGV[0] =~ /^(--version|-v)$/){
		print("$CurVer\n"); exit 0
	}elsif($ARGV[0] =~ /^-.*/){
		TFL::FAIL(1, __LINE__, "Incorrect argument(s) specified")
	}else{
		last
	}

	shift(@ARGV)
}

TFL::DepChkPortable('man');

my @Execs;
foreach(split(':', $ENV{PATH})){
	foreach(glob("$_/*")){
		if(-f $_ and -x $_ and -r $_){
			push(@Execs, basename($_, '/'))
		}
	}
}

@Execs = uniq(sort({lc($a) cmp lc($b)} @Execs));

my @Mans;
if(-d '/usr/share/man'){
	# I really don't want to do this, but any method I try with Perl is very slow.
	@Mans = glob('/usr/share/man/man[1-8]/*.[1-8].gz');
	print(readpipe("man -f @Execs 2> /dev/null") =~ s/\([0-8]\)\s+//gr)
}else{
	TFL::FAIL(1, __LINE__, "Unable to find the man pages.")
}
