#!/usr/bin/env perl
#cito M:755 O:0 G:0 T:/usr/bin/redshifter
#----------------------------------------------------------------------------------
# Project Name      - PerlProjects/redshifter
# Started On        - Fri 19 Apr 23:05:28 BST 2019
# Last Change       - Thu  2 Jan 23:09:35 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

use strict;
use warnings;
use autodie;
use TFL 'Err', 'DepChk'; # <-- libtfl-perl (>= 2020-01-02)

no warnings 'uninitialized';

my $CurVer = "2020-01-02";

my ($Temp, $GammasNow);
my $Buffer = "$ENV{HOME}/.config/redshifter.tmp";

mkdir("$ENV{HOME}/.config") unless -d "$ENV{HOME}/.config";

DepChk('redshift');

Err(1, "At least one argument is required.") if $#ARGV == -1;

# Example: GetSetValue('>', 6500) | GetSetValue('<')
# $_[0] = Whether to read ('<') or write ('>') to the file.
# $_[1] = The new gamma value (int) to set.
sub GetSetValue{
	open(my $FH, $_[0], $Buffer);

	print($FH "$_[1]\n") if $_[0] eq '>';
	chomp($GammasNow = <$FH>) if $_[0] eq '<';

	close($FH)
}

# Get current value if file available, else set default value.
GetSetValue('<') ? -f -r -w $Buffer : GetSetValue('>', 6500);

if($ARGV[0] =~ '^(--version|-v)$'){
	print("$CurVer\n")
}elsif($ARGV[0] =~ '^(--reset|-r)$'){
	GetSetValue('>', '6500');
	system('redshift -o -O 6500K')
}elsif($ARGV[0] =~ '^(--increment|-i)$'){
	$Temp = $GammasNow + $ARGV[1];

	Err(1, "Gamma setting '25000' is the highest.") unless $Temp <= 25000;

	GetSetValue('>', $Temp);
	system("redshift -o -O ${Temp}K")
}elsif($ARGV[0] =~ '^(--decrement|-d)$'){
	$Temp = $GammasNow - $ARGV[1];

	Err(1, "Gamma setting '1000' is the lowest.") unless $Temp >= 1000;

	GetSetValue('>', $Temp);
	system("redshift -o -O ${Temp}K")
}
