#!/usr/bin/perl

#----------------------------------------------------------------------------------
# Project Name      - perlmisc/rpii (ar-pee)
# Started On        - Mon  6 May 20:54:08 BST 2019
# Last Change       - Mon  6 May 21:01:58 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

use strict;
use warnings;
use autodie;

my $_VERSION_ = "2019-05-06";

print("Rudimentary Perl Interactive Interpreter. ($_VERSION_)\n\n");

while(){
	print(STDOUT '>>> ');
	eval <>;
	print(STDOUT "\n")
}
