#!/usr/bin/perl

#----------------------------------------------------------------------------------
# Project Name      - perlmisc/up
# Started On        - Wed 17 Apr 13:13:34 BST 2019
# Last Change       - Sun  5 May 11:50:13 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# A Perl rewrite of up() previously found in my .bash_functions.
#----------------------------------------------------------------------------------

use strict;
use warnings;
use autodie;

my $_VERSION_ = "2019-05-05";

sub FAIL{
	printf("[L%0.4d] ERROR: %s\n", $_[1], $_[2]);
	if($_[0] == 1){exit 1}
}

while($ARGV[0]){
	if($ARGV[0] =~ /^(--help|-h|-\?)$/){
		print("USAGE: up [[--help|-h|-?] | [--version|-v]]\n");
		exit 0
	}elsif($ARGV[0] =~ /^(--version|-v)$/){
		print("$_VERSION_\n");
		exit 0
	}else{
		FAIL(1, __LINE__, "Incorrect argument(s) specified")
	}

	shift(@ARGV)
}

my $FILE = '/proc/uptime';
FAIL(1, __LINE__, "File '$FILE' not found.") if not -f $FILE;
FAIL(1, __LINE__, "Read access for '$FILE' is denied.") if not -r $FILE;

open(my $FH, '<', $FILE);

while(<$FH>){
	my @ARRAY = split(" ", $_);
	my $HOUR = int($ARRAY[0] / 60 / 60);
	my $MIN = int($ARRAY[0] / 60 - ($HOUR * 60));

	# Use correct grammar.
	my $HOUR_S = "s";
	my $MIN_S = "s";
	$HOUR_S = '' if $HOUR <= 1;
	$MIN_S = '' if $MIN <= 1;

	printf(
		"UP: %d hour%s and %d minute%s.\n",
		$HOUR, $HOUR_S, $MIN, $MIN_S
	)
}

close($FH)
