#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/tudu
#----------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/completions/tudu
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Wed 15 Jan 16:27:12 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# This is the bash completion script for tudu
#----------------------------------------------------------------------------------

_tudu(){
	GetArgs(){
		local IsOpts F1 F2 _
		tudu -h | while read F1 F2 _; do
			if [ "$F1" = 'OPTS:' ]; then
				printf '%s ' "${F2//|/ }"
				IsOpts='true'
			elif [ "$IsOpts" = 'true' ]; then
				case $F1 in
					-*)
						printf '%s ' "${F1//|/ }"
						[ -z "$F1" ] && break ;;
					*) continue ;;
				esac
			fi
		done
	}

	COMPREPLY=(`compgen -W "$(GetArgs)" -- "$2"`)
}

complete -F _tudu tudu
