#!/usr/bin/env bash
#cito -M=644 -O=0 -G=0 -T=/usr/share/bash-completion/completions/apt-undo-install
#----------------------------------------------------------------------------------
# Project Name      - PerlProjects/completions/apt-undo-install
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Fri 27 Dec 22:19:04 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# This is the bash completion script for apt-undo-install.
#----------------------------------------------------------------------------------

_aptundoinstall(){
	GetArgs(){
		local CurLine Word

		while read -a CurLine; do
			if ! [[ "$IS_OPTS_LINE" == 'true' && "$Old" =~ ^[A-Z]+:$ ]]; then
				case "${CurLine[0]}" in
					OPTS:)
						Word="${CurLine[1]//|/ } " ;;
					-*)
						Word="${CurLine[0]//|/ } " ;;
				esac

				if [ "$Word" == '--output-only:F ' ]; then
					printf '%s ' --output-only:{col,list,desc}
				else
					printf '%s ' "$Word"
				fi

				local Old=${CurLine[0]/OPTS:}
			else
				break
			fi
		done <<< "$(apt-undo-install -h)"
	}

	COMPREPLY=($(compgen -W "$(GetArgs)" -- "$2"))
}

complete -F _aptundoinstall -o default apt-undo-install
