#!/usr/bin/env bash

#----------------------------------------------------------------------------------
# Project Name      - PerlProjects/completions/git-tudu
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Thu 26 Dec 23:28:23 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# This is the bash completion script for git-tudu
#----------------------------------------------------------------------------------

_gittudu(){
	GetArgs(){
		local IsOpts F1 F2 _
		git-tudu -h | while read F1 F2 _; do
			if [ "$F1" = 'OPTS:' ]; then
				printf '%s ' "${F2//|/ }"
				IsOpts='true'
			elif [ "$IsOpts" = 'true' ]; then
				case $F1 in
					-*)
						printf '%s ' "${F1//|/ }"
						[ -z "$F1" ] && break ;;
					*) continue ;;
				esac
			fi
		done
	}

	COMPREPLY=(`compgen -W "$(GetArgs)" -- "$2"`)
}

complete -F _gittudu git-tudu
