#!/usr/bin/env bash
#cito -M:644 -O:0 -G:0 -T:/usr/share/bash-completion/completions/previewer
#----------------------------------------------------------------------------------
# Project Name      - PerlProjects/completions/previewer
# Started On        - Sat 20 Apr 12:29:28 BST 2019
# Last Change       - Fri 27 Dec 22:24:27 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# This is the bash completion script for previewer.
#----------------------------------------------------------------------------------

_previewer(){
	GetArgs(){
		local IsOpts F1 F2 _
		previewer -h | while read F1 F2 _; do
			if [ "$F1" = 'OPTS:' ]; then
				printf '%s ' "${F2//|/ }"
				IsOpts='true'
			elif [ "$IsOpts" = 'true' ]; then
				case $F1 in
					-*)
						printf '%s ' "${F1//|/ }"
						[ -z "$F1" ] && break ;;
					*) continue ;;
				esac
			fi
		done
	}

	case $2 in
		-*)
			COMPREPLY=(`compgen -W "$(GetArgs)" -- "$2"`) ;;
		*)
			PKGList=(`_xfunc dpkg _comp_dpkg_installed_packages`)
			COMPREPLY=(`compgen -W "${PKGList[*]}" -- "$2"`) ;;
	esac
}

complete -F _previewer previewer
