#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - PerlProjects/completions/previewer
# Started On        - Sat 20 Apr 12:29:28 BST 2019
# Last Change       - Thu  9 May 12:57:33 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# This is the bash completion script for previewer.
#----------------------------------------------------------------------------------

_arg_list_previewer(){
	local X

	while read -a X; do
		if [ "$IS_OPTS_LINE" == "true" ]\
		&& [[ "$OLD" =~ ^[A-Z]+:$ ]]; then
			break
		fi

		case "${X[0]}" in
			OPTS:)
				IS_OPTS_LINE="true"
				printf "%s " "${X[1]//|/ }" ;;
			-*)
				printf "%s " "${X[0]//|/ }" ;;
		esac

		local OLD="${X[0]/OPTS:}"
	done <<< "$(/usr/bin/previewer -h)"
}

_option_previewer(){
	COMPREPLY=($(compgen -W "$(_arg_list_previewer)" -- "$2"))
}

complete -F _option_previewer -o default previewer
