#!/bin/bash
#cito -M=644 -O=0 -G=0 -T=/usr/share/bash-completion/completions/wcdl
#----------------------------------------------------------------------------------
# Project Name      - PerlProjects/completions/wcdl
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Fri 27 Dec 22:19:39 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# This is the bash completion script for wcdl.
#----------------------------------------------------------------------------------

_wcdl(){
	local Current=${COMP_WORDS[$COMP_CWORD]}
	local Previous=${COMP_WORDS[$COMP_CWORD - 1]}

	GetArgs(){
		local IsOpts F1 F2 _
		wcdl -h | while read F1 F2 _; do
			if [ "$F1" = 'OPTS:' ]; then
				printf '%s ' "${F2//|/ }"
				IsOpts='true'
			elif [ "$IsOpts" = 'true' ]; then
				case $F1 in
					-*)
						printf '%s ' "${F1//|/ }"
						[ -z "$F1" ] && break ;;
					*) continue ;;
				esac
			fi
		done
	}

	GetCats(){
		while read -a X; do
			if [ "${X[0]}" -a "${X[0]}" != "CATEGORY" ]; then
				printf "%s " "${X[0]}"
			fi
		done <<< "$(wcdl --colorless --show-categories)"
	}

	if [[ $Previous =~ ^(--resolution|-r)$ ]]; then
		COMPREPLY=($(compgen -W "$(wcdl --show-resolutions)" -- "$2"))
	elif [[ "$Current" == -* ]]; then
		COMPREPLY=($(compgen -W "$(GetArgs)" -- "$2"))
	elif [[ $Previous =~ ^(--dest|-D)$ ]]; then
		COMPREPLY=($(compgen -o default -- "$2"))
	else
		COMPREPLY=($(compgen -W "$(GetCats)" -- "$2"))
	fi
}

complete -F _wcdl wcdl
