#!/usr/bin/env perl
#cito M:755 O:0 G:0 T:/usr/bin/getip
#----------------------------------------------------------------------------------
# Project Name      - PerlProjects/source/getip
# Started On        - Wed  8 May 14:35:49 BST 2019
# Last Change       - Wed 15 Jan 16:25:13 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

use strict;
use warnings;
use autodie;
use File::Basename 'basename';
use TFL 'Err'; # <-- libtfl-perl (>= 2020-01-03)

no warnings 'uninitialized';

my $CurVer = "2020-01-15";

my $Domain = "https://whatismyipaddress.com";

sub Usage{
	print(qq{            @{[uc($TFL::PROGNAME)]} ($CurVer)
		            $TFL::AUTHOR

		            View your internal and/or external IP address.

		SYNTAX:     $TFL::PROGNAME [OPTS]

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --internal|-i           - Show only the internal IP address.
		            --external|-e           - Show only the external IP address.
		            --ip-only|-I            - Show only the IP address.

		SITE:       $Domain
	} =~ tr/\t//dr)
}

my $Internal = 'true';
my $External = 'true';
my $IntExtDetected = 0;
my $IntStr = 'Internal IP: ';
my $ExtStr = 'External IP: ';

while(length($ARGV[0]) > 0){
	if($ARGV[0] =~ '^(--help|-h|-\?)$'){
		Usage(); exit(0)
	}elsif($ARGV[0] =~ '^(--version|-v)$'){
		print("$CurVer\n"); exit(0)
	}elsif($ARGV[0] =~ '^(--internal|-i)$'){
		$IntExtDetected++; $Internal = 'true'; $External = 'false'
	}elsif($ARGV[0] =~ '^(--external|-e)$'){
		$IntExtDetected++; $Internal = 'false'; $External = 'true'
	}elsif($ARGV[0] =~ '^(--ip-only|-I)$'){
		$IntStr = ''; $ExtStr = ''
	}else{
		Err(1, "Incorrect argument(s) specified")
	}

	shift(@ARGV)
}

Err(1, "Either '--internal|-i' or '--external|-e'.") if $IntExtDetected == 2;

if($Internal){
	use Net::Address::IP::Local; # <-- libnet-address-ip-local-perl (>= 0.1.2-3)

	print($IntStr . Net::Address::IP::Local->public() . "\n")
}

if($External){
	use LWP::UserAgent; # <-- libwww-perl (>= 6.15-1)

	my $UA = LWP::UserAgent->new();
	$UA->max_redirect(1);
	$UA->protocols_allowed(['http', 'https']);
	$UA->agent('Mozilla/5.0');

	foreach(split("\n", $UA->get($Domain)->decoded_content())){
		foreach(@{[split(' ', $_)]}){
			if($_ =~ /[0-9]+\.[0-9]+\.[0-9]+\.[0-9]/){
				print($_ =~ s/(.*)<\/span>$/$ExtStr$1/r . "\n");
				exit(0)
			}
		}
	}
}
